# -*- coding: utf-8 -*-
"""IDS Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6vy8IBvkE9EW0S8I38KQgzIboOb4J0p
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score, roc_curve, classification_report,
    confusion_matrix, balanced_accuracy_score, f1_score,
    precision_recall_curve, auc as auc_score
)

# Seed random generators using N-number of <Yoon Seol Jang>
SEED = 11177942
np.random.seed(SEED)
random.seed(SEED)

num = pd.read_csv("/content/drive/MyDrive/IDS capstone/rmpCapstoneNum.csv", header=None)
qual = pd.read_csv("/content/drive/MyDrive/IDS capstone/rmpCapstoneQual.csv", header=None)
tags = pd.read_csv("/content/drive/MyDrive/IDS capstone/rmpCapstoneTags.csv", header=None)

num.columns = [
    "avg_rating",
    "avg_difficulty",
    "n_ratings",
    "pepper",
    "take_again_percent",
    "n_online_ratings",
    "male",
    "female"
]

qual.columns = ["major", "university", "state"]

tag_names = [
    "tough_grader", "good_feedback", "respected", "lots_to_read",
    "participation_matters", "dont_skip_class", "lots_of_homework",
    "inspirational", "pop_quizzes", "accessible", "so_many_papers",
    "clear_grading", "hilarious", "test_heavy", "graded_by_few_things",
    "amazing_lectures", "caring", "extra_credit", "group_projects",
    "lecture_heavy"
]

tags.columns = tag_names

df = pd.concat([qual, num, tags], axis=1)

df.head(20)

df.isna().sum().reindex(df.columns)

# Columns to check for overlapping missing values
cols_to_check = [
    "major", "university", "state",
    "avg_rating", "avg_difficulty", "n_ratings",
    "pepper", "n_online_ratings"
]

# Create a missing-value mask for each selected column
nan_masks = {c: df[c].isna() for c in cols_to_check}

# Identify rows that are missing in all selected columns simultaneously
all_same_nan = np.logical_and.reduce(list(nan_masks.values()))
all_same_nan.sum()

"""-> All selected columns share the same 19,889 rows with missing values"""

# Identify professors who received zero counts across all qualitative teaching tags
count_all_zero_tags = (df[tag_names].sum(axis=1) == 0).sum()
count_all_zero_tags

# Identify rows where all tag values are zero
all_zero_tag = df[tag_names].sum(axis=1) == 0

# Among those rows, compute the proportion with missing major
n_all_zero_tags = all_zero_tag.sum()
n_major_nan_in_all_zero = df.loc[all_zero_tag, "major"].isna().sum()

n_all_zero_tags, n_major_nan_in_all_zero

"""-> Those 19,889 rows also have all Tags values missing (all zero)"""

# Remove those 19,889 missing rows
cols_to_check = [
    "major", "university", "state",
    "avg_rating", "avg_difficulty", "n_ratings",
    "pepper", "n_online_ratings"
]
missing_mask = df[cols_to_check].isna().all(axis=1)

# Drop rows that are missing across all selected columns simultaneously
df = df.loc[~missing_mask].copy()
df.shape

# Identify rows with ambiguous gender labels (male = female = 0 or male = female = 1)

count_00 = ((df["male"] == 0) & (df["female"] == 0)).sum()
count_00

count_11 = ((df["male"] == 1) & (df["female"] == 1)).sum()
count_11

# Count the number of rows with zero ratings
n_zero_ratings = (df["n_ratings"] == 0).sum()
n_zero_ratings

count_all_zero_tags = (df[tag_names].sum(axis=1) == 0).sum()
count_all_zero_tags

"""Now 5459 rows have missing Tags

"""

# Create a single gender variable:
# 0 = male, 1 = female, 2 = unknown / ambiguous
df["gender"] = 2  # default to unknown

df.loc[(df["male"] == 1) & (df["female"] == 0), "gender"] = 0
df.loc[(df["male"] == 0) & (df["female"] == 1), "gender"] = 1

# Compute the total number of tags per professor across all 20 tag columns
df["total_tag_count"] = df[tag_names].sum(axis=1)

# Select the top 10 rows with the highest total tag counts
top10_tag_rows = df.sort_values("total_tag_count", ascending=False).head(10)

# Display relevant columns for inspection
top10_tag_rows[["total_tag_count"] + tag_names]

df["total_tag_count"] = df[tag_names].sum(axis=1)

# Normalize each tag by the row-wise total tag count
# Rows with zero total tags are left as zero
df[tag_names] = df[tag_names].div(df["total_tag_count"], axis=0).fillna(0)

# Drop rows with number of ratings less than 4
df = df[df["n_ratings"] >= 4]
df

df.isna().sum().reindex(df.columns)

"""# 1

"""

d = df[(df["gender"].isin([0, 1])) & (df["avg_rating"].notna())].copy()

male = d.loc[d["gender"] == 0, "avg_rating"].astype(float).values
female = d.loc[d["gender"] == 1, "avg_rating"].astype(float).values

print(f"Median (Male)   = {np.median(male):.3f}")
print(f"Median (Female) = {np.median(female):.3f}")

U_stat, p_one = stats.mannwhitneyu(
    male, female, alternative="greater"
)

alpha = 0.005
sig = "SIGNIFICANT" if p_one < alpha else "NOT significant"

print(f"Mann–Whitney U statistic = {U_stat:.0f}")
print(f"One-sided p-value = {p_one:.6g} (alpha = {alpha})")
print(f"Result: {sig}")

plt.boxplot([male, female], labels=["Male", "Female"])
plt.ylabel("Average Rating")
plt.title("Average Rating by Gender (Mann–Whitney U)")
plt.show()

"""# 2

"""

median_m = np.median(male)
median_f = np.median(female)

print("Q2: Gender Difference in Spread (Median Absolute Deviation/Dispersion)")
print("=" * 70)
print("\nDescriptive Statistics:")
print(f"Median (Male):   {median_m:.4f}")
print(f"Median (Female): {median_f:.4f}")

print("\n" + "=" * 70)
print("PERMUTATION TEST")
print("=" * 70)
print("H0: The dispersion of ratings is identical for both groups")
print("Test statistic: Median absolute deviation (MAD) difference (Male - Female)")

mad_m = stats.median_abs_deviation(male, nan_policy='omit')
mad_f = stats.median_abs_deviation(female, nan_policy='omit')
delta_mad_observed = mad_m - mad_f
print(f"\nObserved MAD difference = {delta_mad_observed:.4f}")

combined = np.concatenate([male, female])
n_male = len(male)
n_female = len(female)

print(f"Sample sizes: Male = {n_male}, Female = {n_female}")

n_permutations = 10000
rng_perm = np.random.default_rng(SEED)

print(f"Running {n_permutations} permutations...")

permuted_diffs = np.empty(n_permutations)

for i in range(n_permutations):
    shuffled = rng_perm.permutation(combined)

    group1 = shuffled[:n_male]
    group2 = shuffled[n_male:]

    mad1 = stats.median_abs_deviation(group1, nan_policy='omit')
    mad2 = stats.median_abs_deviation(group2, nan_policy='omit')
    permuted_diffs[i] = mad1 - mad2

more_extreme = np.abs(permuted_diffs) >= np.abs(delta_mad_observed)
p_val_perm = np.mean(more_extreme)

alpha = 0.005
sig_perm = "SIGNIFICANT" if p_val_perm < alpha else "NOT significant"

print("\nPermutation test results:")
print(f"  Number of permutations: {n_permutations}")
print(f"  Permutations as extreme as observed: {more_extreme.sum()} / {n_permutations}")
print(f"  p-value = {p_val_perm:.6f} (alpha = {alpha})")
print(f"  Result: {sig_perm}")

if sig_perm == "SIGNIFICANT":
    if delta_mad_observed > 0:
        print(f"\nInterpretation: Male professors have HIGHER MAD (more spread)")
    else:
        print(f"\nInterpretation: Female professors have HIGHER MAD (more spread)")
else:
    print(f"\nInterpretation: No significant difference in MAD")

plt.figure(figsize=(12, 6))
plt.hist(permuted_diffs, bins=60, color="lightblue", edgecolor="black", alpha=0.7,
         label="Null distribution (10,000 permutations)")
plt.axvline(delta_mad_observed, color="red", lw=3, linestyle="-",
            label=f"Observed = {delta_mad_observed:.4f}")
plt.axvline(-delta_mad_observed, color="red", lw=3, linestyle="-", alpha=0.5)
plt.axvline(0, color="orange", lw=2, linestyle=":", label="No difference (H0)")

critical_values = np.percentile(permuted_diffs, [0.25, 99.75])
plt.axvline(critical_values[0], color="darkred", lw=1, linestyle="--", alpha=0.5)
plt.axvline(critical_values[1], color="darkred", lw=1, linestyle="--", alpha=0.5)

plt.xlabel("MAD Difference (Male - Female)", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
plt.title("Q2: Permutation Test - Null Distribution of MAD Differences", fontsize=14)
plt.legend(fontsize=10)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

print("\n" + "=" * 70)
print("CONCLUSION")
print("=" * 70)
if sig_perm == "SIGNIFICANT":
    print(f"There IS a statistically significant difference in spread/MAD")
    print(f"between male and female professors (p = {p_val_perm:.6f} < {alpha})")
    if delta_mad_observed > 0:
        print(f"Male professors have MORE variable ratings (larger MAD)")
    else:
        print(f"Female professors have MORE variable ratings (larger MAD)")
else:
    print(f"There is NO statistically significant difference in spread/MAD")
    print(f"between male and female professors (p = {p_val_perm:.6f} >= {alpha})")
print("=" * 70)

"""# 3"""

def bootstrap_stat(sample, stat_fn, n_boot=5000, rng=None):
    """Bootstrap a statistic from a sample."""
    if rng is None:
        rng = np.random.default_rng()
    n = len(sample)
    boots = np.empty(n_boot, dtype=float)
    for i in range(n_boot):
        resample = sample[rng.integers(0, n, n)]
        boots[i] = stat_fn(resample)
    return boots


def ci_percentile(boots, alpha=0.05):
    """Compute percentile-based confidence interval from bootstrap distribution."""
    return (np.percentile(boots, 100 * alpha / 2),
            np.percentile(boots, 100 * (1 - alpha / 2)))

rng_q3 = np.random.default_rng(SEED)
n_boot = 5000

boot_median_male = bootstrap_stat(male, np.median, n_boot=n_boot, rng=rng_q3)
boot_median_female = bootstrap_stat(female, np.median, n_boot=n_boot, rng=rng_q3)
boot_median_diff = boot_median_male - boot_median_female

median_diff_obs = np.median(male) - np.median(female)
ci_median = ci_percentile(boot_median_diff, alpha=0.05)

boot_sd_male = bootstrap_stat(male, np.std, n_boot=n_boot, rng=rng_q3)
boot_sd_female = bootstrap_stat(female, np.std, n_boot=n_boot, rng=rng_q3)
boot_sd_diff = boot_sd_male - boot_sd_female

sd_diff_obs = np.std(male) - np.std(female)
ci_sd = ci_percentile(boot_sd_diff, alpha=0.05)

print("Q3: Effect Size Estimation for Rating Bias and Spread Bias")
print("=" * 70)

print("EFFECT 1: BIAS IN AVERAGE RATING (Median Difference)")
print(f" Observed Median Difference (M - F): {median_diff_obs:.4f}")
print(f" 95% Bootstrap CI: [{ci_median[0]:.4f}, {ci_median[1]:.4f}]")

print("EFFECT 2: BIAS IN SPREAD (Standard Deviation Difference)")
print(f" Observed SD Difference (M - F): {sd_diff_obs:.4f}")
print(f" 95% Bootstrap CI: [{ci_sd[0]:.4f}, {ci_sd[1]:.4f}]")
print("=" * 70)

plt.figure(figsize=(10, 6))
plt.hist(boot_median_diff, bins=50, color="skyblue", edgecolor="black", alpha=0.7)
plt.axvline(median_diff_obs, color="red", lw=2, label=f"Observed = {median_diff_obs:.4f}")
plt.axvline(ci_median[0], color="purple", ls="--", lw=2, label="95% CI bounds")
plt.axvline(ci_median[1], color="purple", ls="--", lw=2)
plt.axvline(0, color="orange", ls=":", lw=2, label="No difference")
plt.xlabel("Median Difference (Male - Female)")
plt.ylabel("Frequency")
plt.title("Q3: Bootstrap Distribution of Median Difference")
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(boot_sd_diff, bins=50, color="lightcoral", edgecolor="black", alpha=0.7)
plt.axvline(sd_diff_obs, color="red", lw=2, label=f"Observed SD Diff = {sd_diff_obs:.4f}")
plt.axvline(ci_sd[0], color="purple", ls="--", lw=2, label="95% CI bounds")
plt.axvline(ci_sd[1], color="purple", ls="--", lw=2)
plt.axvline(0, color="orange", ls=":", lw=2, label="No difference in spread")
plt.xlabel("Difference in Standard Deviation (Male - Female)")
plt.ylabel("Frequency")
plt.title("Q3: Bootstrap Distribution of Difference in Rating Spread (SD)")
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

print("" + "=" * 70)
print("SUMMARY")
print("=" * 70)
print("Effect size 1 captures central tendency differences (median bias), while effect size 2")
print("captures dispersion differences (spread bias). Both are accompanied by 95% bootstrap CIs.")
print("=" * 70)

"""# 4"""

alpha = 0.005
alpha_corr = alpha / 20

rows = []
for tag in tag_names:
    male_vals = d.loc[d["gender"] == 0, tag].astype(float).values
    female_vals = d.loc[d["gender"] == 1, tag].astype(float).values

    U, p = stats.mannwhitneyu(male_vals, female_vals, alternative="two-sided")

    rows.append({
        "tag": tag,
        "U_stat": U,
        "p_value": p,
        "sig_bonf": p < alpha_corr
    })

res = pd.DataFrame(rows).sort_values("p_value").reset_index(drop=True)

top3 = res.head(3)
bot3 = res.tail(3)

print("Most gendered (lowest p-values):")
print(top3[["tag", "U_stat", "p_value", "sig_bonf"]].to_string(index=False))

print("\nLeast gendered (highest p-values):")
print(bot3[["tag", "U_stat", "p_value", "sig_bonf"]].to_string(index=False))

plot_df = res.copy()
plot_df["neglog10p"] = -np.log10(plot_df["p_value"])
plt.scatter(plot_df["neglog10p"], plot_df["tag"])
plt.axvline(-np.log10(alpha_corr), linestyle="--", linewidth=1)
plt.xlabel("−log10(p-value)")
plt.ylabel("Tag")
plt.title("Gender Differences in Tags")
plt.show()

"""# 5"""

d_q5 = df[(df["gender"].isin([0, 1])) & (df["avg_difficulty"].notna())].copy()

male_diff = d_q5.loc[d_q5["gender"] == 0, "avg_difficulty"].astype(float).values
female_diff = d_q5.loc[d_q5["gender"] == 1, "avg_difficulty"].astype(float).values

n_m_diff, n_f_diff = len(male_diff), len(female_diff)
median_m_diff, median_f_diff = np.median(male_diff), np.median(female_diff)
median_diff = median_m_diff - median_f_diff

print("Q5: Gender Difference in Average Difficulty")
print("=" * 70)
print(f"\nSample sizes: Male = {n_m_diff}, Female = {n_f_diff}")
print(f"\nMedian (Male):   {median_m_diff:.4f}")
print(f"Median (Female): {median_f_diff:.4f}")
print(f"Median difference (M − F) = {median_diff:.4f}")

stat_mw, p_mw = stats.mannwhitneyu(male_diff, female_diff, alternative='two-sided')

alpha = 0.005
sig = "SIGNIFICANT" if p_mw < alpha else "NOT significant"

print(f"\nMann-Whitney U test (two-sided):")
print(f"  U-statistic = {stat_mw:.2f}")
print(f"  p-value = {p_mw:.6g} (alpha = {alpha})")
print(f"  Result: {sig}")

plt.figure(figsize=(8, 5))
plt.boxplot([male_diff, female_diff], labels=["Male", "Female"])
plt.ylabel("Average Difficulty")
plt.title("Q5: Average Difficulty by Gender")
plt.grid(axis='y', alpha=0.3)
plt.show()

"""# 6"""

def bootstrap_stat(sample, stat_fn, n_boot=5000, rng=None):
    """
    Bootstrap a statistic from a sample.

    Parameters:
    - sample: array-like, the observed data
    - stat_fn: function that computes the statistic (e.g., np.mean, np.median)
    - n_boot: number of bootstrap replications
    - rng: random number generator

    Returns:
    - boots: array of bootstrap statistics
    """
    if rng is None:
        rng = np.random.default_rng()
    n = len(sample)
    boots = np.empty(n_boot, dtype=float)
    for i in range(n_boot):
        resample = sample[rng.integers(0, n, n)]  # resample WITH replacement
        boots[i] = stat_fn(resample)
    return boots

def ci_percentile(boots, alpha=0.05):
    """
    Compute percentile-based confidence interval from bootstrap distribution.

    Parameters:
    - boots: array of bootstrap statistics
    - alpha: significance level (default 0.05 for 95% CI)

    Returns:
    - (lower, upper): tuple of CI bounds
    """
    return (np.percentile(boots, 100 * alpha / 2),
            np.percentile(boots, 100 * (1 - alpha / 2)))

rng_q6 = np.random.default_rng(SEED)
n_boot = 5000

print("Q6: Effect Size Estimation Based on Q5 Test")
print("=" * 70)
print("Estimating median difference effect size with 95% bootstrap CI")
print("Bootstrapping with 5000 replications...\n")

boot_median_male = bootstrap_stat(male_diff, np.median, n_boot=n_boot, rng=rng_q6)
boot_median_female = bootstrap_stat(female_diff, np.median, n_boot=n_boot, rng=rng_q6)
boot_median_diff = boot_median_male - boot_median_female

median_diff_obs = np.median(male_diff) - np.median(female_diff)
ci_median_diff = ci_percentile(boot_median_diff, alpha=0.05)

print("MEDIAN DIFFERENCE (difficulty location effect from Q5)")
print("Measures central tendency difference in difficulty between groups")
print(f"  Observed median (Male):   {np.median(male_diff):.4f}")
print(f"  Observed median (Female): {np.median(female_diff):.4f}")
print(f"  Median difference (Male - Female) = {median_diff_obs:.4f}")
print(f"  95% CI = [{ci_median_diff[0]:.4f}, {ci_median_diff[1]:.4f}]")

print("\n" + "=" * 70)
if ci_median_diff[0] > 0:
    print("CONCLUSION: Males are rated as significantly MORE difficult")
    print("            (The entire 95% CI is above zero)")
elif ci_median_diff[1] < 0:
    print("CONCLUSION: Males are rated as significantly LESS difficult")
    print("            (The entire 95% CI is below zero)")
else:
    print("CONCLUSION: The 95% CI includes zero")
    print("            The difference may not be statistically significant")
print("=" * 70)

plt.figure(figsize=(10, 6))
plt.hist(boot_median_diff, bins=50, color="steelblue", edgecolor="black", alpha=0.7)
plt.axvline(median_diff_obs, color="red", lw=2, label=f"Observed = {median_diff_obs:.4f}")
plt.axvline(ci_median_diff[0], color="purple", ls="--", lw=2, label="95% CI bounds")
plt.axvline(ci_median_diff[1], color="purple", ls="--", lw=2)
plt.axvline(0, color="orange", ls=":", lw=2, label="No difference")
plt.xlabel("Median Difficulty Difference (Male - Female)")
plt.ylabel("Frequency")
plt.title("Q6: Bootstrap Distribution of Median Difficulty Difference")
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)
print("Effect size quantifies the magnitude of difficulty difference found in Q5:")
print(f"  - Median difference: {median_diff_obs:.4f} difficulty points")
print("\nThe 95% bootstrap confidence interval quantifies uncertainty in the estimate.")
print("=" * 70)

"""# 7"""

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


num_cols = [
    "avg_difficulty", "n_ratings", "pepper",
    "take_again_percent", "n_online_ratings"
]

print("Correlation Matrix")
print(df[num_cols].corr())

base_num = df[
    ["avg_difficulty", "n_ratings", "pepper",
     "take_again_percent", "n_online_ratings"]
]

gender_dummies = pd.get_dummies(df["gender"], prefix="gender", drop_first=True)

X = pd.concat([base_num, gender_dummies], axis=1)
y = df["avg_rating"]
d = pd.concat([X, y], axis=1).dropna()
X, y = d[X.columns], d["avg_rating"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED
)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

ridge = Ridge(alpha=1.0)
ridge.fit(X_train_s, y_train)

y_pred = ridge.predict(X_test_s)
r2_q7 = r2_score(y_test, y_pred)
rmse_q7 = rmse(y_test, y_pred)

print("\nQ7 Results")
print(f"R^2  = {r2_q7:.4f}")
print(f"RMSE = {rmse_q7:.4f}")

coef_q7 = pd.Series(ridge.coef_, index=X.columns)
print("Most predictive factor:", coef_q7.abs().idxmax())

coef_q7_sorted = coef_q7.sort_values(key=np.abs, ascending=False)

plt.figure(figsize=(6, 4))
coef_q7_sorted.plot(kind="barh")
plt.axvline(0, linestyle="--", linewidth=1)
plt.xlabel("Standardized Ridge Coefficient")
plt.title("Q7: Numerical Predictors of Average Rating")
plt.tight_layout()
plt.show()

"""# 8"""

tag_corr = df[tag_names].corr()
print("Correlation Matrix")
print(tag_corr)

X = df[tag_names]
y = df["avg_rating"]

d = pd.concat([X, y], axis=1).dropna()
X, y = d[tag_names], d["avg_rating"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED
)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

ridge = Ridge(alpha=1.0)
ridge.fit(X_train_s, y_train)

y_pred = ridge.predict(X_test_s)

r2_q8 = r2_score(y_test, y_pred)
rmse_q8 = rmse(y_test, y_pred)

print("\nQ8 Results")
print(f"R^2  = {r2_q8:.4f}")
print(f"RMSE = {rmse_q8:.4f}")

coef_q8 = pd.Series(ridge.coef_, index=tag_names)
print("Most predictive tag:", coef_q8.abs().idxmax())

coef_q8_sorted = coef_q8.sort_values(key=np.abs, ascending=False).head(10)

plt.figure(figsize=(6, 4))
coef_q8_sorted[::-1].plot(kind="barh")
plt.axvline(0, linestyle="--", linewidth=1)
plt.xlabel("Standardized Ridge Coefficient")
plt.title("Q8: Top Tag Predictors of Average Rating")
plt.tight_layout()
plt.show()

"""# 9"""

X = df[tag_names]
y = df["avg_difficulty"]

d = pd.concat([X, y], axis=1).dropna()
X, y = d[tag_names], d["avg_difficulty"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED
)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

ridge = Ridge(alpha=1.0)
ridge.fit(X_train_s, y_train)

y_pred = ridge.predict(X_test_s)

r2_q9 = r2_score(y_test, y_pred)
rmse_q9 = rmse(y_test, y_pred)

print("\nQ9 Results")
print(f"R^2  = {r2_q9:.4f}")
print(f"RMSE = {rmse_q9:.4f}")

coef_q9 = pd.Series(ridge.coef_, index=tag_names)
print("Most predictive tag:", coef_q9.abs().idxmax())

coef_q9_sorted = coef_q9.sort_values(key=np.abs, ascending=False).head(10)

plt.figure(figsize=(6, 4))
coef_q9_sorted[::-1].plot(kind="barh")
plt.axvline(0, linestyle="--", linewidth=1)
plt.xlabel("Standardized Ridge Coefficient")
plt.title("Q9: Top Tag Predictors of Average Difficulty")
plt.tight_layout()
plt.show()

"""# 10"""

print("Q10: Predicting 'Pepper' Status")
print("=" * 60)

numerical_features = [
    "avg_rating", "avg_difficulty", "n_ratings",
    "take_again_percent", "n_online_ratings"
]

all_features = numerical_features + tag_names
X_base = df[all_features].copy()
gender_dummies = pd.get_dummies(df["gender"], prefix="gender", drop_first=True)
X = pd.concat([X_base, gender_dummies], axis=1)

y = df["pepper"]
data_combined = pd.concat([X, y], axis=1).dropna()
X = data_combined[X.columns]
y = data_combined["pepper"]

print(f"\nDataset size: {len(X)} samples")
print(f"Features: {X.shape[1]} predictors")

class_counts = y.value_counts()
print(f"\nClass distribution:")
print(f"  No pepper (0): {class_counts[0]} ({class_counts[0]/len(y)*100:.1f}%)")
print(f"  Pepper (1):    {class_counts[1]} ({class_counts[1]/len(y)*100:.1f}%)")
print(f"  Imbalance ratio: {class_counts[0]/class_counts[1]:.2f}:1")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

print(f"\nTrain set: {len(X_train)} samples")
print(f"Test set:  {len(X_test)} samples")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

logreg = LogisticRegression(
    class_weight='balanced',
    max_iter=1000,
    random_state=SEED,
    solver='lbfgs'
)

print("\nTraining Logistic Regression with balanced class weights...")
logreg.fit(X_train_scaled, y_train)

y_pred = logreg.predict(X_test_scaled)
y_pred_proba = logreg.predict_proba(X_test_scaled)[:, 1]

print("\n" + "=" * 60)
print("MODEL PERFORMANCE METRICS")
print("=" * 60)

auroc = roc_auc_score(y_test, y_pred_proba)
print(f"\nAU(ROC)C = {auroc:.4f}")

precision, recall, _ = precision_recall_curve(y_test, y_pred_proba)
auprc = auc_score(recall, precision)
print(f"AU(PRC) = {auprc:.4f}")

balanced_acc = balanced_accuracy_score(y_test, y_pred)
print(f"Balanced Accuracy = {balanced_acc:.4f}")

f1 = f1_score(y_test, y_pred)
print(f"F1-Score = {f1:.4f}")

print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(f"                Predicted")
print(f"                No    Yes")
print(f"Actual  No    {cm[0,0]:5d} {cm[0,1]:5d}")
print(f"        Yes   {cm[1,0]:5d} {cm[1,1]:5d}")


print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['No Pepper', 'Pepper']))

coefficients = pd.Series(logreg.coef_[0], index=X.columns)
top_10_features = coefficients.abs().sort_values(ascending=False).head(10)

print("\nTop 10 Most Predictive Features (by |coefficient|):")
for i, (feature, coef_abs) in enumerate(top_10_features.items(), 1):
    coef_val = coefficients[feature]
    direction = "+" if coef_val > 0 else "-"
    print(f"{i:2d}. {feature:25s} {direction} {abs(coef_val):.4f}")

fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (AUC = {auroc:.3f})')
plt.plot([0, 1], [0, 1], color='red', lw=2, linestyle='--', label='Random classifier')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Q10: ROC Curve for Pepper Prediction')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(recall, precision, color='green', lw=2, label=f'PR curve (AUC = {auprc:.3f})')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Q10: Precision-Recall Curve')
plt.legend(loc="lower left")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

top_features_plot = coefficients.sort_values(key=lambda x: x.abs(), ascending=True).tail(15)

plt.figure(figsize=(10, 6))
colors = ['red' if x < 0 else 'blue' for x in top_features_plot]
plt.barh(range(len(top_features_plot)), top_features_plot.values, color=colors, alpha=0.7)
plt.yticks(range(len(top_features_plot)), top_features_plot.index)
plt.axvline(0, color='black', linestyle='--', linewidth=1)
plt.xlabel('Logistic Regression Coefficient (log-odds)')
plt.title('Q10: Top 15 Predictors of Pepper Status\n(Red = Decreases likelihood, Blue = Increases likelihood)')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

print("\n" + "=" * 60)
print("Summary: Logistic Regression successfully handles class imbalance")
print("using balanced class weights and provides interpretable coefficients.")
print("=" * 60)

"""# Extra Credit"""

MIN_N = 200
d = df[["major", "avg_rating", "avg_difficulty"]].dropna()

major_counts = d["major"].value_counts()
keep_majors = major_counts[major_counts >= MIN_N].index
d = d[d["major"].isin(keep_majors)]

rows = []
for m, g in d.groupby("major"):
    res = stats.linregress(g["avg_difficulty"].astype(float), g["avg_rating"].astype(float))
    rows.append({
        "major": m,
        "n": len(g),
        "slope": res.slope,
        "slope_stderr": res.stderr
    })

slopes = pd.DataFrame(rows).sort_values("slope")

plot_df = pd.concat([slopes.head(5), slopes.tail(5)], axis=0).copy()


plt.figure(figsize=(7, 5))
plt.errorbar(
    x=plot_df["slope"],
    y=plot_df["major"],
    xerr=1.96 * plot_df["slope_stderr"],
    fmt="o"
)
plt.axvline(0, linestyle="--", linewidth=1)
plt.xlabel("Slope (Avg Rating change per +1 Difficulty)")
plt.title(f"Rating–Difficulty Tradeoff by Major (Top 5 vs Bottom 5, n ≥ {MIN_N})")
plt.tight_layout()
plt.show()

